#cloud-config

# Configured according to 0.7.9 config schema:
# http://bit.ly/cloud-init-0-7-9-examples

groups:
  - k8s-admin

users:
${users}

write_files:

  - path: /etc/NetworkManager/conf.d/00-do-not-manage-dns.conf
    owner: root:root
    permissions: 0440
    encoding: gzip
    content: !!binary |
      ${network_manager_dns_disabled}

  - path: /etc/modules-load.d/br_netfilter.conf
    owner: root:root
    permissions: 0440
    content: |
      br_netfilter

  - path: /etc/sysctl.d/k8s.conf
    owner: root:root
    permissions: 0440
    content: |
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1

  - path: /etc/default/path
    owner: root:root
    permissions: 0444
    content: |
      PATH=/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

  - path: /etc/sysconfig/iptables
    owner: root:root
    permissions: 0640
    encoding: gzip
    content: !!binary |
      ${iptables}

  - path: /etc/sysconfig/ip6tables
    owner: root:root
    permissions: 0640
    encoding: gzip
    content: !!binary |
      ${iptables}

  - path: /var/lib/kubernetes/cloud-provider.config
    owner: root:root
    permissions: 0400
    encoding: gzip
    content: !!binary |
      ${cloud_provider_config}

  - path: /etc/ssl/ca.crt
    owner: root:root
    permissions: 0644
    encoding: gzip
    content: !!binary |
      ${tls_ca_crt}

  - path: /etc/ssl/ca.key
    owner: root:root
    permissions: 0400
    encoding: gzip
    content: !!binary |
      ${tls_ca_key}

  - path: /opt/bin/defaults.sh
    owner: root:root
    permissions: 0755
    encoding: gzip
    content: !!binary |
      ${defaults_sh}

  - path: /etc/systemd/system/defaults.service
    owner: root:root
    permissions: 0644
    encoding: gzip
    content: !!binary |
      ${defaults_service}

  - path: /opt/bin/control-plane-online.sh
    owner: root:root
    permissions: 0755
    encoding: gzip
    content: !!binary |
      ${control_plane_online_sh}

  - path: /etc/default/control-plane-online
    owner: root:root
    permissions: 0644
    encoding: gzip
    content: !!binary |
      ${control_plane_online_env}

  - path: /etc/systemd/system/control-plane-online.service
    owner: root:root
    permissions: 0644
    encoding: gzip
    content: !!binary |
      ${control_plane_online_service}

  - path: /opt/bin/newcert.sh
    owner: root:root
    permissions: 0755
    encoding: gzip
    content: !!binary |
      ${newcert_sh}

  - path: /etc/default/gencerts
    owner: root:root
    permissions: 0644
    encoding: gzip
    content: !!binary |
      ${gencerts_env}

  - path: /opt/bin/gencerts.sh
    owner: root:root
    permissions: 0755
    encoding: gzip
    content: !!binary |
      ${gencerts_sh}

  - path: /etc/default/genkcfgs
    owner: root:root
    permissions: 0644
    encoding: gzip
    content: !!binary |
      ${genkcfgs_env}

  - path: /opt/bin/genkcfgs.sh
    owner: root:root
    permissions: 0755
    encoding: gzip
    content: !!binary |
      ${genkcfgs_sh}

  - path: /etc/default/bins
    owner: root:root
    permissions: 0644
    encoding: gzip
    content: !!binary |
      ${bins_env}

  - path: /opt/bin/bins.sh
    owner: root:root
    permissions: 0755
    encoding: gzip
    content: !!binary |
      ${bins_sh}

  - path: /etc/systemd/system/bins.service
    owner: root:root
    permissions: 0644
    encoding: gzip
    content: !!binary |
      ${bins_service}

  - path: /etc/profile.d/path.sh
    owner: root:root
    permissions: 0755
    encoding: gzip
    content: !!binary |
      ${path_sh}

  - path: /etc/profile.d/prompt.sh
    owner: root:root
    permissions: 0755
    encoding: gzip
    content: !!binary |
      ${prompt_sh}

  - path: /etc/cni/net.d/10-bridge.conf
    owner: root:root
    permissions: 0644
    encoding: gzip
    content: !!binary |
      ${cni_bridge_config}

  - path: /etc/cni/net.d/99-loopback.conf
    owner: root:root
    permissions: 0644
    encoding: gzip
    content: !!binary |
      ${cni_loopback_config}

  - path: /etc/containerd/config.toml
    owner: root:root
    permissions: 0644
    encoding: gzip
    content: !!binary |
      ${containerd_config}

  - path: /etc/systemd/system/containerd.service
    owner: root:root
    permissions: 0644
    encoding: gzip
    content: !!binary |
      ${containerd_service}

  - path: /etc/default/kube-init-pre
    owner: root:root
    permissions: 0644
    encoding: gzip
    content: !!binary |
      ${kube_init_pre_env}

  - path: /etc/systemd/system/kube-init-pre.service
    owner: root:root
    permissions: 0644
    encoding: gzip
    content: !!binary |
      ${kube_init_pre_service}

  - path: /var/lib/kubelet/kubelet-config.yaml
    owner: root:root
    permissions: 0644
    encoding: gzip
    content: !!binary |
      ${kubelet_config}

  - path: /etc/default/kubelet
    owner: root:root
    permissions: 0644
    encoding: gzip
    content: !!binary |
      ${kubelet_env}

  - path: /etc/systemd/system/kubelet.service
    owner: root:root
    permissions: 0644
    encoding: gzip
    content: !!binary |
      ${kubelet_service}

  - path: /var/lib/kube-proxy/kube-proxy-config.yaml
    owner: root:root
    permissions: 0644
    encoding: gzip
    content: !!binary |
      ${kube_proxy_config}

  - path: /etc/default/kube-proxy
    owner: root:root
    permissions: 0644
    encoding: gzip
    content: !!binary |
      ${kube_proxy_env}

  - path: /etc/systemd/system/kube-proxy.service
    owner: root:root
    permissions: 0644
    encoding: gzip
    content: !!binary |
      ${kube_proxy_service}

runcmd:
  - [ mkdir, -p, /opt/containerd,
                 /var/lib/containerd,
                 /var/run/containerd,
                 /var/run/containerd/runsc,
                 /var/lib/kubernetes,
                 /var/lib/kubelet,
                 /var/lib/kube-proxy ]

  - [ sysctl, --system ]

  #- [ setenforce, 0 ]

  - [ systemctl, daemon-reload ]

  - [ systemctl, restart, iptables, 
                          ip6tables,
                          systemd-modules-load.service ]

  - [ systemctl, enable, defaults.service,
                         bins.service,
                         control-plane-online.service,
                         containerd.service,
                         kube-init-pre.service,
                         kubelet.service,
                         kube-proxy.service ]

  - [ systemctl, start, kube-proxy.service ]

# Commented out unless needed.
packages:
  - lsof
  - bind-utils
  - socat
  - conntrack-tools
