root = "${root_dir}"
state = "${state_dir}"
subreaper = true

[grpc]
  address = "${sock_file}"
  uid = 0
  gid = 0

[plugins]
  [plugins.cri.containerd]
    snapshotter = "overlayfs"
    [plugins.cri.containerd.default_runtime]
      runtime_type = "io.containerd.runtime.v1.linux"
      runtime_engine = "${bin_dir}/runc"
      runtime_root = ""
    [plugins.cri.containerd.untrusted_workload_runtime]
      runtime_type = "io.containerd.runtime.v1.linux"
      runtime_engine = "${bin_dir}/runsc"
      runtime_root = "${runsc_root_dir}"
